#!/usr/bin/env bash

DEVICE_ID="wlp60s0"

#SHOW_IP="1"

IP=$(ip addr | grep $DEVICE_ID | awk '/inet/ {print $2}')

STATUS=$(nmcli device status | grep -i "$DEVICE_ID" | awk '{$1=""; $2=""; print $0}' | \
        sed "s/\s\+/ /g" | \
        sed "s/ connected //" | \
        sed "s/--//g")

if [[ ! -z $SHOW_IP ]]; then 
        echo $IP $STATUS
else
        echo $STATUS
fi
