#!/usr/bin/env bash

xautolock -time 10 -locker slock &

~/.fehbg 
xbindkeys
xset r rate 200 60

while true; do
        dwmstatus
        sleep 1s
done &


while true; do
    # Log stderror to a file 
    dwm 2> ~/.dwm.log
    # No error logging
    #dwm >/dev/null 2>&1
done
