#!/usr/bin/env sh

SCHOOL_PATH=$HOME/Documents/school

usage() {
    echo "Usage $0 COURSE"
}

get_date_path() {
    date +%m/%d
}

main() {
    if [ -z $1 ]; then
        usage
        exit 2
    fi

    if [ ! -d $SCHOOL_PATH/$1 ]; then
        echo "Course directory doesn't exist"
        exit 2
    fi

    course=$1
    path=$SCHOOL_PATH/$course/$(get_date_path)

    mkdir -p $path

    echo $course $(date +%H:%M) >> $path/notes.md
    cd $path
    nvim notes.md
}

main $@
