#!/usr/bin/env bash

function run_desktop() {
	`grep '^Exec' $1 | tail -1 | sed 's/^Exec=//' | sed 's/%.//' | sed 's/^"//g' | sed 's/" *$//g'` &
}

for file in $(find ~/.config/autostart -type f); do
	run_desktop $file
done
